# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-30 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
